import type { NextPage } from 'next';
import * as S from './Home.styled';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <S.Grid>
        </S.Grid>
      </S.Main>
      <S.Footer>
      </S.Footer>
    </S.Container>
  )
}

export default Home
